#pragma once

#include <cstdint>
#include <memory>

#include "CAD/geometry/volume.hpp"
#include "CAD/geometry/graph.hpp"

namespace CAD{
    namespace geometry{
        class Tree{
        private:
            enum class OPERATION : uint8_t{
                // Placeholder, no graph
                EMPTY,
                // End node, left and right are empty
                NONE,
                // Empty node, graph generated by union of left and right (l OR r, l+r)
                UNION,
                // Empty node, graph generated by difference of left from right (l AND NOT r, l-r)
                DIFFERENCE,
                // Empty node, graph generated by difference of right from left (NOT l AND r, r-l)
                DIFFERENCE_R,
                // Empty node, graph generated by intersection of left and right (l AND r, l*r)
                INTERSECTION
            };

            OPERATION op;

            std::unique_ptr<Volume> volume = nullptr;

            Tree *left = nullptr, *right = nullptr;
        public:
            Tree();
            Tree(std::unique_ptr<Volume> p);
            ~Tree();
            void reset();

            template <class T>
            Tree *operator+(T *t);
            template <class T>
            Tree *operator-(T *t);
            template <class T>
            Tree *operator*(T *t);
        };
    }
}