#pragma once

#include <cstdint>
#include <memory>

#include "CAD/geometry/volume.hpp"
#include "CAD/geometry/graph.hpp"

namespace CAD{
    namespace geometry{
        class Tree : public Volume {
        private:
            enum class OPERATION : uint8_t{
                // Invalid, should not occcur (used internally as placeholder)
                NULL_OP,
                // Empty graph
                EMPTY,
                // Graph generated by union of left and right (l OR r, l+r)
                UNION,
                // Graph generated by difference of left from right (l AND NOT r, l-r)
                DIFFERENCE,
                // Graph generated by intersection of left and right (l AND r, l*r)
                INTERSECTION
            };

            OPERATION op;

            Volume *left = nullptr, *right = nullptr;
        public:
            Tree();
        private:
            Tree(Tree *t);
        public:
            ~Tree();
            void reset();

            // Union operator
            void operator+=(Volume *t);
            // Difference opearator (Note: Does nothing to an empty tree)
            void operator-=(Volume *t);
            // Intersection operator (Note: Does nothing to an empty tree)
            void operator*=(Volume *t);

            bool inside(glm::vec3 point) override;
            glm::vec3 project(glm::vec3 origin, glm::vec3 ray) override;

            Graph generateGraph() override;
            Graph unionGraph(Volume *other) override;
            Graph differenceGraph(Volume *other) override;
            Graph intersectionGraph(Volume *other) override;
        };
    }
}